In [1]:
import numpy as np
import pandas as pd

In [ ]:
x = np.array([[1, 1, 1, 0, 0],
                  [0, 1, 1, 1, 0],
                  [0, 0, 1, 1, 1],
                  [0, 0, 1, 1, 0],
                  [0, 1, 1, 0, 0]],
                 dtype='float')

In [8]:
input_data_size=32
input_channel1=np.random.choice([1,0],size=[input_data_size,input_data_size])
input_channel2=np.random.choice([1,0],size=[input_data_size,input_data_size])
input_channel3=np.random.choice([1,0],size=[input_data_size,input_data_size])

In [9]:
input_data=np.array([input_channel1,input_channel2,input_channel3])

In [10]:
filt_size=5
filt_channel1=np.random.choice([1,0],size=[filt_size,filt_size])
filt_channel2=np.random.choice([1,0],size=[filt_size,filt_size])
filt_channel3=np.random.choice([1,0],size=[filt_size,filt_size])

In [14]:
filt=np.array([filt_channel1,filt_channel2,filt_channel3])

In [19]:
# lets suppose the output number of channles is 5
output_size=28
output_channel1=np.random.choice([1,0],size=[output_size,output_size])
output_channel2=np.random.choice([1,0],size=[output_size,output_size])
output_channel3=np.random.choice([1,0],size=[output_size,output_size])
output_channel4=np.random.choice([1,0],size=[output_size,output_size])
output_channel5=np.random.choice([1,0],size=[output_size,output_size])

In [24]:
output_data=np.array([output_channel1,output_channel2,output_channel3,output_channel4,output_channel5])

In [26]:
output_data[0].shape

(28, 28)

In [42]:
np.array(range(1,26)).reshape(5,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [43]:
# x = np.array([[1, 1, 1, 0, 0],
#                   [0, 1, 1, 1, 0],
#                   [0, 0, 1, 1, 1],
#                   [0, 0, 1, 1, 0],
#                   [0, 1, 1, 0, 0]],
#                  dtype='float')

x=np.array(range(1,26)).reshape(5,5)

In [44]:
filter_size=3
stride=1
index_list=[]
vertical_start_pos=[]
i=0
j=0
while j<x.shape[1]-1:
    j=(i+filter_size-1)
    index_list.append((i,j))
    vertical_start_pos.append(i)
    i+=stride
print("Index list for horizontal direction ->{}".format(index_list))
print("Vertical start indexes ->{}".format(vertical_start_pos))

Index list for horizontal direction ->[(0, 2), (1, 3), (2, 4)]
Vertical start indexes ->[0, 1, 2]


In [45]:
v_mat=[]
for v_start in vertical_start_pos:
    h_mat=[]
    for indexes in index_list:    
        sub_matrice=[]
        for vertical_start in range(v_start,v_start+filter_size):    
            sub_matrice.append(x[vertical_start,][indexes[0]:indexes[1]+1])
        h_mat.append(np.array(sub_matrice))
    v_mat.append(h_mat)    

In [46]:
x

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [76]:
dx=np.array(range(1,10)).reshape(3,3)
act=np.array(range(1,10)).reshape(3,3)
act

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [72]:
coord

[(1, 2)]

In [78]:
v_mat[0][1]

array([[ 2,  3,  4],
       [ 7,  8,  9],
       [12, 13, 14]])

In [92]:
act

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [106]:
number=3
grad=''
for i in range(3):
    for j in range(3):
        result=np.where(v_mat[i][j]==number)
        coord=list(zip(result[0], result[1]))
        print("{}th number is at {}".format(number,coord))
        if len(coord)!=0:
            grad=grad+"act["+str(act[coord[0]])+"]"+"* "+"dx["+str(dx[i][j])+"]"
            grad=grad+"+"
grad=grad[:-1]            

3th number is at [(0, 2)]
3th number is at [(0, 1)]
3th number is at [(0, 0)]
3th number is at []
3th number is at []
3th number is at []
3th number is at []
3th number is at []
3th number is at []


In [107]:
grad

'act[3]* dx[1]+act[2]* dx[2]+act[1]* dx[3]'

In [100]:
act

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [47]:
for h_mat_set in v_mat:
    aa=h_mat_set
    cc=''
    for j in range(aa[0].shape[0]):
        for i in range(len(aa)):
            cc=cc+str(aa[i][j])+" "
        cc=cc+'\n'
    print(cc)    

[1 2 3] [2 3 4] [3 4 5] 
[6 7 8] [7 8 9] [ 8  9 10] 
[11 12 13] [12 13 14] [13 14 15] 

[6 7 8] [7 8 9] [ 8  9 10] 
[11 12 13] [12 13 14] [13 14 15] 
[16 17 18] [17 18 19] [18 19 20] 

[11 12 13] [12 13 14] [13 14 15] 
[16 17 18] [17 18 19] [18 19 20] 
[21 22 23] [22 23 24] [23 24 25] 

